import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

// ── Interfaces ──────────────────────────────────────────────

interface EmailAttachment {
  filename: string;
  content: string; // base64 encoded
}

interface SendEmailOptions {
  to: string;
  subject: string;
  html: string;
  attachments?: EmailAttachment[];
}

interface ResendResponse {
  id?: string;
  message?: string;
  statusCode?: number;
}

// ── Service ─────────────────────────────────────────────────

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  private readonly apiKey: string | undefined;
  private readonly fromAddress = 'onboarding@resend.dev';

  constructor(private readonly configService: ConfigService) {
    this.apiKey = this.configService.get<string>('RESEND_API_KEY');

    if (!this.apiKey) {
      this.logger.warn(
        'RESEND_API_KEY is not set — EmailService will not be operational',
      );
    }
  }

  get isConfigured(): boolean {
    return !!this.apiKey;
  }

  async sendEmail(options: SendEmailOptions): Promise<{ success: boolean; id?: string; error?: string }> {
    if (!this.apiKey) {
      return { success: false, error: 'RESEND_API_KEY is not configured' };
    }

    const payload = {
      from: this.fromAddress,
      to: [options.to],
      subject: options.subject,
      html: options.html,
      attachments: options.attachments,
    };

    try {
      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const data = (await response.json()) as ResendResponse;

      if (!response.ok) {
        const errMsg = data.message || `HTTP ${response.status}`;
        this.logger.error(`Resend API error: ${errMsg}`);
        return { success: false, error: errMsg };
      }

      this.logger.log(`Email sent to ${options.to} (id: ${data.id})`);
      return { success: true, id: data.id };
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      this.logger.error(`Email send failed: ${msg}`);
      return { success: false, error: msg };
    }
  }

  /**
   * Build a styled HTML email body for a presentation export.
   */
  buildPresentationEmailHtml(
    title: string,
    slideCount: number,
    format: string,
  ): string {
    return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0a0804;color:#f5f0e8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Inter,Helvetica,Arial,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:32px 24px;">
    <div style="text-align:center;margin-bottom:32px;">
      <div style="display:inline-block;background:#f97316;color:#0a0804;font-size:11px;font-weight:700;padding:4px 12px;border-radius:4px;letter-spacing:1.5px;text-transform:uppercase;margin-bottom:16px;">PITCHABLE</div>
      <h1 style="font-size:24px;font-weight:700;color:#f5f0e8;margin:12px 0 8px 0;">${title}</h1>
      <p style="font-size:14px;color:#8a7a6a;margin:0;">
        ${slideCount} slides &middot; Exported as ${format.toUpperCase()}
      </p>
    </div>
    <div style="background:#171210;border:1px solid #2e221a;border-radius:8px;padding:24px;text-align:center;">
      <p style="color:#d4c8b8;font-size:14px;line-height:1.6;margin:0 0 16px 0;">
        Your presentation is attached to this email.
      </p>
      <p style="color:#6b5b4b;font-size:12px;margin:0;">
        Generated by Pitchable &middot; AI Presentation Builder
      </p>
    </div>
  </div>
</body>
</html>`;
  }
}
